# Generated by Django 5.1.7 on 2025-03-28 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('date_field', models.DateField(default=datetime.date.today)),
                ('time_field',models.TimeField()),
            ],
        ),
    ]
