# Generated by Django 5.1.6 on 2025-04-06 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0004_remove_enquiry_table_date_remove_enquiry_table_time_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry_table",
            name="date_field",
        ),
        migrations.RemoveField(
            model_name="enquiry_table",
            name="time_field",
        ),
        migrations.AddField(
            model_name="enquiry_table",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="enquiry_table",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
