# Generated by Django 5.1.7 on 2025-08-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_enquiry_table_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
