# Generated by Django 5.2.5 on 2026-01-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_safename'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_table',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
