# Generated by Django 5.2.5 on 2026-01-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_enquiry_table_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SafeName',
        ),
        migrations.RemoveField(
            model_name='enquiry_table',
            name='time',
        ),
        migrations.RemoveField(
            model_name='enquiry_table_1',
            name='people',
        ),
        migrations.RemoveField(
            model_name='enquiry_table_1',
            name='time',
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enquiry_table',
            name='subject',
            field=models.CharField(default='Table Booking', max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry_table_1',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
