# Generated by Django 5.1.6 on 2025-04-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry_table",
            name="people",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="enquiry_table",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="enquiry_table",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="enquiry_table",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="enquiry_table",
            name="subject",
            field=models.CharField(max_length=255),
        ),
    ]
