# Generated by Django 5.1.6 on 2025-04-06 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_enquiry_table_people_alter_enquiry_table_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry_table",
            name="date_field",
        ),
        migrations.RemoveField(
            model_name="enquiry_table",
            name="time_field",
        ),
        migrations.AddField(
            model_name="enquiry_table",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="enquiry_table",
            name="time",
            field=models.TimeField(null=True),
        ),
    ]
