# Generated by Django 5.1.7 on 2025-04-08 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_enquiry_table_date_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry_table_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('people', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
    ]
